# Tested successfully on the hiyouga/verl:ngc-th2.6.0-cu126-vllm0.8.4-flashinfer0.2.2-cxx11abi0 image.

set -x
export VLLM_USE_CUDA_MALLOC_ASYNC=1
export TOKENIZERS_PARALLELISM=true
export NCCL_DEBUG=WARN
export VLLM_LOGGING_LEVEL=WARN
export CUDA_VISIBLE_DEVICES=4,5,6,7
export HYDRA_FULL_ERROR=1
export WANDB_GROUP=verl_debug
export VLLM_DISABLE_SYMMETRIC_MEMORY=1
export VLLM_USE_V1=0


# export RAY_USE_MULTIPROCESSING_CPU_COUNT=1
export RAY_DISABLE_DOCKER_CPU_WARNING=1
export RAY_DISABLE_DASHBOARD=1


N_GPUS=4 # verl defaults to (and only supports) hybrid engines

# train script
proj_dir=YOUR_PROJECT_PATH
# Default listwise dataset:
# train_dset=$proj_dir/dataset/confit_v3_listwise/train_dataset.parquet
# test_dset=$proj_dir/dataset/confit_v3_listwise/test_dataset.parquet
#
# Rerank difficulty/acc dataset (generated by run_create_rerank_difficulty_dataset.sh):
train_dset=$proj_dir/dataset/difficulty/rerank_difficulty_train_dataset.parquet
test_dset=$proj_dir/dataset/difficulty/rerank_difficulty_test_dataset.parquet
reward_fpath=$proj_dir/confit_v3/trainer/reward_fns_listwise_reason.py
reward_fn_name=my_reward_fn_rearank


model_name=Qwen/Qwen3-8B
train_bsize=32  # for train_bsize in all_train_data; do rollout
micro_train_bsize=8
per_device_micro_batch_size=1 
experiment_name=qwen3_8B_rearank_rl

# ray stop --force || true
# ray start --head --num-gpus=4 --num-cpus=64 --disable-usage-stats



python3 -m verl.trainer.main_ppo \
  algorithm.adv_estimator=grpo \
  data.train_files=$train_dset \
  data.val_files=$test_dset \
  data.train_batch_size=$train_bsize \
  data.max_prompt_length=7200 \
  data.max_response_length=2400 \
  data.filter_overlong_prompts=True \
  data.truncation='error' \
  custom_reward_function.path=$reward_fpath \
  custom_reward_function.name=$reward_fn_name \
  actor_rollout_ref.model.path=$model_name \
  actor_rollout_ref.model.use_remove_padding=True \
  actor_rollout_ref.model.enable_gradient_checkpointing=True \
  actor_rollout_ref.actor.optim.lr=1e-6 \
  actor_rollout_ref.actor.ppo_mini_batch_size=$micro_train_bsize \
  actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=$per_device_micro_batch_size \
  actor_rollout_ref.actor.use_kl_loss=True \
  actor_rollout_ref.actor.kl_loss_coef=0.01 \
  actor_rollout_ref.actor.kl_loss_type=low_var_kl \
  actor_rollout_ref.actor.entropy_coeff=0 \
  actor_rollout_ref.actor.fsdp_config.param_offload=False \
  actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
  actor_rollout_ref.rollout.name=vllm \
  actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
  actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
  actor_rollout_ref.rollout.n=32 \
  actor_rollout_ref.rollout.max_num_batched_tokens=16384 \
  actor_rollout_ref.rollout.enable_chunked_prefill=True \
  actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=$per_device_micro_batch_size \
  actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=$per_device_micro_batch_size \
  actor_rollout_ref.ref.fsdp_config.param_offload=True \
  algorithm.use_kl_in_reward=False \
  trainer.logger='["console","wandb"]' \
  trainer.project_name='confit_v3' \
  trainer.experiment_name=$experiment_name \
  trainer.n_gpus_per_node=$N_GPUS \
  trainer.nnodes=1 \
  trainer.save_freq=100 \
  trainer.test_freq=5 \
  trainer.total_epochs=2 \
  trainer.log_val_generations=5;

